export {default as Navbar} from './Navbar/Navbar'
export {default as Home} from './Home/Home'
export {default as What} from './What/What'
export {default as Why} from './Why/Why'
export {default as ServicesCard} from './ServicesCard/ServicesCard'